# for app

APP_DEFAULT_BRACKETS_FORMAT = '[]'
APP_DEFAULT_DELIMITER_PARSED_TREE = '▏'     # U+258F (Left one eighth block)
APP_DEFAULT_DELIMITER_PROB = '▁'            # U+2581 (Lower one eighth block)
APP_DEFAULT_JSONIFY_KEY_RESULT = 'result'
APP_DEFAULT_LOG_DIR = 'log'
APP_DEFAULT_MODEL_PATH = 'models/main/cfparser-app.model'
APP_DEFAULT_PCFG_FORMAT = 'pcfg'
APP_DEFAULT_ROOT_NONTERMINAL = 'S'
APP_DEFAULT_SAMPLE_FORMAT = '{}{}{}{}'
APP_DEFAULT_UNUSED_NONTERMINAL = 'UNUSED'
APP_DEFAULT_VITERBI_MODEL = 'viterbi'
